qsub PWSKHLMYTZNYKO-UHFFFAOYSA-N_conf_0.pbs
qsub PWSKHLMYTZNYKO-UHFFFAOYSA-N_conf_1.pbs
qsub PWSKHLMYTZNYKO-UHFFFAOYSA-N_conf_2.pbs
qsub PWSKHLMYTZNYKO-UHFFFAOYSA-N_conf_3.pbs
qsub PWSKHLMYTZNYKO-UHFFFAOYSA-N_conf_4.pbs
